# Generated by Django 5.2.1 on 2026-02-17 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_backup_codes_user_mfa_enabled_user_mfa_secret'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE app_user DROP COLUMN IF EXISTS two_factor_secret;",
            reverse_sql=""
        ),
    ]
