# Generated by Django 5.2.1 on 2026-02-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_zombie_column_two_factor_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='active_agents',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='company_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='industry',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='metrics',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
