# Generated by Django 5.2.1 on 2026-02-17 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_workspace_active_agents_workspace_company_size_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE app_workspace ALTER COLUMN industry DROP NOT NULL;
            ALTER TABLE app_workspace ALTER COLUMN company_size DROP NOT NULL;
            ALTER TABLE app_workspace ALTER COLUMN timezone DROP NOT NULL;
            ALTER TABLE app_workspace ALTER COLUMN currency DROP NOT NULL;
            ALTER TABLE app_workspace ALTER COLUMN active_agents DROP NOT NULL;
            ALTER TABLE app_workspace ALTER COLUMN metrics DROP NOT NULL;
            """,
            reverse_sql="""
            ALTER TABLE app_workspace ALTER COLUMN industry SET NOT NULL;
            ALTER TABLE app_workspace ALTER COLUMN company_size SET NOT NULL;
            ALTER TABLE app_workspace ALTER COLUMN timezone SET NOT NULL;
            ALTER TABLE app_workspace ALTER COLUMN currency SET NOT NULL;
            ALTER TABLE app_workspace ALTER COLUMN active_agents SET NOT NULL;
            ALTER TABLE app_workspace ALTER COLUMN metrics SET NOT NULL;
            """
        ),
    ]
